plugins { id 'java-library' }
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
tasks.register('regressionTest', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.balzikz.mathclient.foundation.core.CoreTests'
}
check.dependsOn regressionTest
