plugins {
    id 'com.android.application'
}

android {
    namespace 'com.balzikz.mathclient'
    compileSdk 36

    defaultConfig {
        applicationId 'com.balzikz.mathclient'
        minSdk 23
        targetSdk 36
        versionCode 2
        versionName '0.2.0-alpha'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
