plugins {
    id 'com.android.application'
}

android {
    namespace 'com.balzikz.mathclient'
    compileSdk 36
    ndkVersion '27.0.12077973'

    defaultConfig {
        applicationId 'com.balzikz.mathclient'
        minSdk 23
        targetSdk 36
        versionCode 4
        versionName '0.3.0-alpha'

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++20'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
